#pragma once




#define DEVICE_NAME L"\\Device\\LRMCTRL"

#define HIDDEN_PATH L"\\??\\C:\\windows\\system32\\config\\CONTROLSET"

#define SYMBOLIC_NAME L"\\??\\LRMCTRL"

#define CC_TEST CTL_CODE(FILE_DEVICE_UNKNOWN,0x820,METHOD_BUFFERED, FILE_WRITE_ACCESS | FILE_READ_ACCESS)
#define CC_KILL1 CTL_CODE(FILE_DEVICE_UNKNOWN,0x821,METHOD_BUFFERED, FILE_WRITE_ACCESS | FILE_READ_ACCESS)
#define CC_KILL2 CTL_CODE(FILE_DEVICE_UNKNOWN,0x822,METHOD_BUFFERED, FILE_WRITE_ACCESS | FILE_READ_ACCESS)
#define CC_KILLALL CTL_CODE(FILE_DEVICE_UNKNOWN,0x823,METHOD_BUFFERED, FILE_WRITE_ACCESS | FILE_READ_ACCESS)
#define CC_DEL CTL_CODE(FILE_DEVICE_UNKNOWN,0x824,METHOD_BUFFERED, FILE_WRITE_ACCESS | FILE_READ_ACCESS)
#define CC_DEL2 CTL_CODE(FILE_DEVICE_UNKNOWN,0x825,METHOD_BUFFERED, FILE_WRITE_ACCESS | FILE_READ_ACCESS)
#define DRIVER_LOG_FILENAME L"\\??\\c:\\LRM.log"
#define DRIVER_LOG_FILENAME_DEBUGX L"\\??\\c:\\LRM_DEBUG.log"

#define KC_OPEN_FAILED 0x1
#define KC_SUCCESS 0x77
#define KC_TERMINATE_FAILED 0x2
#define DC_OPEN_FAILED 0x3
#define DC_DELETE_FAILED 0x4
#define DC_SUCCESS 0x77
#define USERPATH_MAX_LEN 1000

#define PRODUCT_MODE 1
#define STRONG_DEBUG 0